apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-ears-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios@sha256:47745d8fc50d785334366c0d0c59287167163e64931843153f94beed61fc07b8
        name: my-go
        resources: {}
status: {}
